name: Build GDExtension

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always
    GODOT_VERSION: "4.2.1"

jobs:
    build:
        name: Build for ${{ matrix.platform.name }}
        runs-on: ${{ matrix.platform.os }}
        strategy:
            fail-fast: false
            matrix:
                platform:
                    - name: Windows
                      os: windows-latest
                      target: x86_64-pc-windows-msvc
                      lib_ext: dll
                    - name: Linux
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      lib_ext: so
                    - name: macOS
                      os: macos-latest
                      target: x86_64-apple-darwin
                      lib_ext: dylib

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.platform.target }}

            - name: Install Linux dependencies
              if: matrix.platform.name == 'Linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y build-essential libclang-dev pkg-config

            - name: Build library
              run: |
                  cargo build --release --target ${{ matrix.platform.target }}

            - name: Create GDExtension output structure
              shell: bash
              run: |
                  mkdir -p "addons/godot_vlc/bin/${{ matrix.platform.name }}"
                  cp "target/${{ matrix.platform.target }}/release/libgodot_vlc.${{ matrix.platform.lib_ext }}" "addons/godot_vlc/bin/${{ matrix.platform.name }}/"
                  
                  # Make sure GDExtension json file exists in the addon folder
                  if [ ! -f "addons/godot_vlc/godot_vlc.gdextension" ]; then
                      mkdir -p addons/godot_vlc
                      cat > addons/godot_vlc/godot_vlc.gdextension << EOF
                  [configuration]
                  entry_symbol = "gdext_rust_init"
                  compatibility_minimum = 4.1

                  [libraries]
                  linux.x86_64 = "res://addons/godot_vlc/bin/Linux/libgodot_vlc.so"
                  windows.x86_64 = "res://addons/godot_vlc/bin/Windows/libgodot_vlc.dll"
                  macos.universal = "res://addons/godot_vlc/bin/macOS/libgodot_vlc.dylib"
                  EOF
                  fi

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: godot-vlc-${{ matrix.platform.name }}
                  path: addons/godot_vlc/

    package:
        name: Package Extension
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v3
              with:
                  path: artifacts

            - name: Create addon package
              run: |
                  mkdir -p godot_vlc/addons/godot_vlc
                  cp -r artifacts/godot-vlc-*/bin godot_vlc/addons/godot_vlc/
                  cp artifacts/godot-vlc-*/*.gdextension godot_vlc/addons/godot_vlc/
                  cd godot_vlc && zip -r ../godot_vlc.zip .

            - name: Upload packaged addon
              uses: actions/upload-artifact@v3
              with:
                  name: godot_vlc_addon
                  path: godot_vlc.zip

            - name: Create Release
              if: startsWith(github.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v1
              with:
                  files: godot_vlc.zip